[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
verbosity = 3
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink/",
]

[profile.default.fuzz]
runs = 1000

[profile.ci]
fuzz = { runs = 10000 }

[rpc_endpoints]
base_mainnet = "${BASE_RPC_URL}"
base_sepolia  = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base_mainnet = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
base_sepolia  = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
